behaviors:
  PathAgent:
    trainer_type: custom_ppo
    hyperparameters:
      batch_size: 256  # Increased for better performance
      buffer_size: 24000  # Increased for more stable learning
      learning_rate: 1.0e-4  # Can try 1.0e-3 or 5.0e-5 depending on training
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 1000  # Adjust based on your environment's length
    summary_freq: 24000  # Lower logging frequency to speed up training
